### ISSUE TITLE
Why is the Ruby Version restricted to version 2

### ISSUE THREAD

**Issue by Garllon** [hausgold/pricehubble#4]
Hi, 

is there a specific reason why the ruby version is restricted to version 2?

https://github.com/hausgold/pricehubble/blob/a568e23405e384d374a459122d39dcfa85ea5527/pricehubble.gemspec#L17

Best regards

**Comment by Jack12816** [comment]
Hey Garllon, Ruby 3 is not yet in the CI matrix. In the next weeks we are going to add support for it.

**Comment by Jack12816** [comment]
I released version 1.0.0 today with `spec.required_ruby_version = '>= 2.5'`, so its more relaxed.
